global using CommunityToolkit.Maui.Alerts;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using PetAdoptionMAUI.Mobile.Models;
global using PetAdoptionMAUI.Mobile.Pages;
global using PetAdoptionMAUI.Mobile.ViewModels;
global using PetAdoptionMAUI.Mobile.Services;
global using PetAdoptionMAUI.Shared.Dtos;
global using PetAdoptionMAUI.Shared.Enumerations;
